### ISSUE TITLE
perl5's future

### ISSUE THREAD

**Issue by xiaoyafeng** [rjbs/QA-LarryWall#7]
Perl 5 is the big sister of perl6, and it has also evolved by a number of smart volunteers. my question is , After one or  two decade, if it is more and more like perl6,  a total different language with perl6 or even worse, dead in next decade?

**Comment by c9s** [comment]
+1

**Comment by msouth** [comment]
+1

[and the post containing the link I followed to get here encouraged commenting on questions...so blame $not_me for the following :)]

Does it matter if it "dies", if perl6 can still run it?

http://www.perl6.org/archive/faq.html (see first or second entry about perl6 being able to run perl 5).

I'm asking because I want to clarify (for the sake of improving a good question here) what you mean by perl 5 "dying".  

It's arguably correct to say that Perl 4 is _still_ dying--[5.22 is removing a feature where you could leave the % off the hash name and keys(), etc would still recognize it](http://perltricks.com/article/165/2015/4/10/A-preview-of-Perl-5-22)--perhaps we can extrapolate from that that perl 5, if it dies, will have a similarly long and healthy death :).

My guess--eventually it will make sense for you to switch your coding, contributions, and attention to perl6, and when that makes sense, you will just do it.  And _when_ that happens will be different for different people based on their needs, codebase, use cases, etc.  

So, my prediction is basically this:

There Will Be More Than One Way To Transition

:)

Great question, I think a lot of people will be wondering about this.
